<html>
<head>
    <meta charset=utf-8"/>
    <title>Layout de Impressão</title>

    <style type="text/css">
        @page {
            margin: 115px 50px 80px 50px;
        }

        #topo {
            background-repeat: no-repeat;
            font-size: 25px;
            text-align: center;
            height: 50px;
            width: 100%;
            position: fixed;
            top: -85px;
            left: 0;
            right: 0;
            margin: auto;
            /*border-bottom: 1px solid #2e2e2e;*/
        }

        .topo_esquerda {
            position: absolute;
            left: 0px;
            top: 0px;
        }

        .topo_direita {
            position: absolute;
            right: 0px;
            top: 0px;
            font-family: Arial;

        }

        #corpo {
            width: 700px;
            position: relative;
            margin: auto;
            top: -30px;
            text-align: justify;
            font-size: 12px;
            font-family: Verdana;
            float: right;
        }

        table {
            background-color: transparent;
            max-width: 100%;
        }

        .table {
            margin-bottom: -25px;
            width: 100%;
        }

        .tablex {
             line-height: 1.42857;
             padding: 0px;
             padding-top: 20px;
             vertical-align: top;
         }

        .tabley {
            line-height: 1.42857;
            padding: 0px;
            padding-top: 20px;
            vertical-align: top;
            border-bottom: black;
        }
        #rodape {
            position: fixed;
            bottom: -15px;
            width: 100%;
            text-align: right;
            border-top: 1px solid #2e2e2e;
        }

        #rodape .page:after {
            content: counter(page);
        }

        .rodape_esquerda {
            position: absolute;
            left: 0px;
            top: 0px;
        }

        .rodape_direita {
            position: absolute;
            right: 0px;
            top: 0px;
        }

        hr{
            border-top: 1px dashed #000000;
            border-bottom: 1px solid #fff;
            color: #fff;
            background-color: #fff;
            height: 1px;

        }

    </style>
</head>
<body>
<!--NÃO ALTERAR A ESTRUTURA DO CÓDIGO - MANTER COMO TOPO / RODAPÉ / CORPO-->
<!--informações do cabeçalho-->
<div id="topo" class="text-center">
    <div class="topo_esquerda">
        <img src="../../../../../public/assets/img/logo/logo-faculdade.png" width="160" height="45">
    </div>
    <div class="topo_direita">


        <!--        <img src="../../../../../public/assets/img/logo/logo-menu.png" width="160" height="45">-->
    </div>
</div>
<!--informações do rodapé-->
<div id="rodape" style="font-size: 8px; font-family: Calibri; font-weight: bold">
    <div class="rodape_esquerda">
        <span class="esquerda">Sistema Integrado de Elaboração de Provas</span>
    </div>
    <div class="rodape_direita">
        <span class="direita">Prova gerada em: </span>
        <?php
        $data = date("d/m/Y");
        echo $data;
        ?>
    </div>
     <div class="page" align="center">

    </div>
</div>
<!--informações do corpo onde será será impresso as questões-->
<div id="corpo">

<div>
    <table class="table tablex" border="1" cellspacing="0" cellpadding="2" style="font-size: 14px">
        <tr>
            <td width="70%">Nome:</td>
            <td width="30%">Matrícula:</td>
        </tr>
        <tr>
            <td>Disciplina:</td>
            <td>Data:</td>
        </tr>
        <tr>
            <td>Curso:</td>
            <td>Turma:</td>
        </tr>
        <tr>
            <td>Professor:</td>
            <td>Nota:</td>
        </tr>
    </table>
    <br>
    <table class="table tabley" cellspacing="0" cellpadding="2" style="font-size: 11px; text-align: justify">
        <tr align="center" style="font-size: 14px;">
            <td colspan="3"><b>Orientações Gerais</b></td>
            <td></td>
        </tr>
        <tr>
            <td width="45%">
                1 - Leia atentamente toda a prova;<br>
                2 - A prova terá uma duração mínima de 30 minutos e somente após este tempo o aluno poderá entregar a prova;<br>
                3 - Para cada questão à somente uma resposta correta.<br>
                4 - Não será corrigida a questão que porventura estiver rasurada e/ou com mais de uma respota marcada;<br>
                5 - Responda as questões à tinta (preto ou azul). Respostas a lápis, não será consideradas;<br>
            </td>
            <td width="5%">  </td>
            <td width="50%">
                6 - A prova é individual e sem consulta;<br>
                7 - Deve permanecer sobre a mesa somente, caneta, lápis e borracha;<br>
                8 - Aparelhos eletrônicos devem ser desligados e guardados com demais materiais debaixo da carteira;<br>
                9 - Não é permitido ausentar-se do local de prova sem a prévia autorização do professor;<br>
                10 - A desobediência a estas instruções poderá implicar no recolhimento da avaliação e na aplicação de nota
                zero aos alunos envolvidos;<br>
            </td>
        </tr>
    </table>
</div>
<div>
    <br><br>
    <hr>
</div>

    <?php
    $nrQuestoes = count($arQuestoesProva);
    if ($nrQuestoes == 0) { ?>
        <div style="text-align: left" class="row form-group">
            <div class="col-md-12">
                <?php
                echo "<h2> Nao existem questoes adicionadas a esta avaliação</h2>";
                ?>
            </div>
        </div>
        <?php
    } else {
        ?>
        <div>
            <?php
            $questaoService = new \Questao\Service\QuestaoService();
            $alternativaquestaoService = new \AlternativaQuestao\Service\AlternativaQuestaoService();
            $i = 1;
            foreach ($arQuestoesProva as $key => $item) {
                $arQuestao = $questaoService->buscar($item['id_questao'])->toArray();
                echo "<p class='questao'> Q.".$i++." - " . str_replace("/assets/kcfinder/upload/images/","../../../../../public/assets/kcfinder/upload/images/",$arQuestao['tx_enunciado']) . "</p>";
                $arAlternativaQuestao = $alternativaquestaoService->fetchAllById(['id_questao' => $item['id_questao']]);
                $j = 'a';
                foreach ($arAlternativaQuestao as $key => $alternativa) {
                    echo "<span>" . $j++ . ") " . str_replace("/assets/kcfinder/upload/images/","../../../../../public/assets/kcfinder/upload/images/",$alternativa['tx_alternativa_questao'] ). "</span><br/>";
                }
                echo "<br/>";
            } ?>
        </div>

        <?php
    }
    ?>

</div>

<?= $dadosProva->getDsProva() ?>
</body>

</html>