<?php
  /** @var $lista \Principal\Service\Principal[] */
?>
<br/><br/>

<div class="page-head">
    <div class="container">
        <div align="center">
            <img src="/assets/img/logo/logo-provatec.jpg" width=" 400px" height="300px"/>
            <br/>
            <p style="font-size: 20px; color: #032a51"> Sistema inteligente para gerar provas</p>


        </div>
    </div>

    <?php //echo $this->Auth()->nm_usuario; ?>
    <?php //echo $this->Auth()->id_usuario; ?>
    <br /><br />
    
</div>



<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $('#competicao').click(function(){
            href = 'evento-evento';
            window.location.href = href;
        });
        $('#academias').click(function(){
            href = 'academia-academia';
            window.location.href = href;
        });
        $('#inscricao').click(function(){
            href = 'inscricoes_evento-inscricoesevento';
            window.location.href = href;
        });
        $('#chavesdeluta').click(function(){
            href = 'chaves_luta-chavesluta';
            window.location.href = href;
        });
    });
</script>